//! Build-time walkthrough content pipeline.
//!
//! The home walkthrough's prose lives in `content/*.md`: a TOML front-matter
//! header (`+++ … +++`) carries the structured chrome each section needs (step,
//! pattern, title, figure caption, tradeoff, recap rows), and the markdown body
//! carries the prose. This script renders each body to HTML and emits the whole
//! set as a `content::SECTIONS` data literal into `$OUT_DIR/content_gen.rs`,
//! which `src/content.rs` includes. Rendering here (not at runtime) keeps the
//! markdown parser out of the shipped WASM bundle.
//!
//! Body prose may carry widget markers on their own line — `:::figure`,
//! `:::tradeoff`, `:::recap` — splitting the body into ordered blocks so a
//! component can slot the figure / tradeoff / recap back into the prose flow.

use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs};

use pulldown_cmark::{Options, Parser, html};
use serde::Deserialize;

/// Sections in reading order: intro, one rung per pattern level, then Bodega's
/// co-design of roster leases with consensus.
const FILES: &[&str] = &[
    "0-intro",
    "1-one-to-one",
    "2-leader-leases",
    "3-quorum-leases",
    "4-roster-leases",
    "5-bodega",
];

/// Front-matter schema. Only `id`, `kind`, and `title` are required; the rest
/// default to empty and are meaningful only for the sections that set them.
#[derive(Deserialize)]
struct FrontMatter {
    id: String,
    kind: String,
    title: String,
    #[serde(default)]
    step: String,
    #[serde(default)]
    pattern: String,
    #[serde(default)]
    figure_caption: String,
    #[serde(default)]
    tradeoff_pro: String,
    #[serde(default)]
    tradeoff_con: String,
    #[serde(default)]
    recap_lead: String,
    #[serde(default)]
    recap: Vec<RecapRow>,
}

#[derive(Deserialize)]
struct RecapRow {
    #[serde(rename = "trait")]
    label: String,
    seen: String,
    #[serde(default)]
    new: bool,
}

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let content_dir = Path::new(&manifest).join("content");
    println!("cargo:rerun-if-changed={}", content_dir.display());

    let mut sections = String::new();
    for name in FILES {
        let path = content_dir.join(format!("{name}.md"));
        println!("cargo:rerun-if-changed={}", path.display());
        let raw =
            fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
        let (fm, body) = split_front_matter(&raw, &path);
        let front: FrontMatter = toml::from_str(fm)
            .unwrap_or_else(|e| panic!("front-matter in {}: {e}", path.display()));
        write!(sections, "{},", render_section(&front, body)).unwrap();
    }

    let generated = format!(
        "// @generated by build.rs from content/*.md — do not edit.\n\
         pub static SECTIONS: &[Section] = &[{sections}];\n"
    );
    let out = Path::new(&env::var("OUT_DIR").unwrap()).join("content_gen.rs");
    fs::write(&out, generated).expect("writing content_gen.rs");
}

/// Split a `+++`-delimited TOML front-matter header from the markdown body.
fn split_front_matter<'a>(raw: &'a str, path: &Path) -> (&'a str, &'a str) {
    let rest = raw.strip_prefix("+++\n").unwrap_or_else(|| {
        panic!(
            "{} must begin with a `+++` front-matter block",
            path.display()
        )
    });
    let end = rest
        .find("\n+++\n")
        .unwrap_or_else(|| panic!("{} front-matter is not closed with `+++`", path.display()));
    (&rest[..end], &rest[end + 5..])
}

/// Render one section to a `Section { … }` Rust literal.
fn render_section(front: &FrontMatter, body: &str) -> String {
    let blocks = split_blocks(body)
        .into_iter()
        .map(|b| match b {
            Block::Html(md) => format!("Block::Html({})", lit(&markdown(md))),
            Block::Figure => "Block::Figure".into(),
            Block::Tradeoff => "Block::Tradeoff".into(),
            Block::Recap => "Block::Recap".into(),
        })
        .collect::<Vec<_>>()
        .join(",");

    let tradeoff = if front.tradeoff_pro.is_empty() {
        "None".into()
    } else {
        format!(
            "Some(({}, {}))",
            lit(&front.tradeoff_pro),
            lit(&front.tradeoff_con)
        )
    };

    let recap = front
        .recap
        .iter()
        .map(|r| {
            format!(
                "RecapRow {{ label: {}, seen: {}, new: {} }}",
                lit(&r.label),
                lit(&r.seen),
                r.new
            )
        })
        .collect::<Vec<_>>()
        .join(",");

    format!(
        "Section {{ id: {}, kind: {}, step: {}, pattern: {}, title: {}, \
         figure_caption: {}, tradeoff: {}, recap_lead: {}, recap: &[{}], blocks: &[{}] }}",
        lit(&front.id),
        lit(&front.kind),
        lit(&front.step),
        lit(&front.pattern),
        lit(&front.title),
        lit(&front.figure_caption),
        tradeoff,
        lit(&front.recap_lead),
        recap,
        blocks,
    )
}

/// An ordered piece of a section body: a chunk of prose markdown, or a widget
/// marker positioned within the prose flow.
enum Block<'a> {
    Html(&'a str),
    Figure,
    Tradeoff,
    Recap,
}

/// Split a body into prose chunks interleaved with `:::name` widget markers.
/// Blank prose chunks (e.g. between two adjacent markers) are dropped, so the
/// prose slices borrow directly from `body`.
fn split_blocks(body: &str) -> Vec<Block<'_>> {
    let mut blocks = Vec::new();
    let mut chunk_start = 0;
    let mut offset = 0;
    for line in body.split_inclusive('\n') {
        let marker = match line.trim() {
            ":::figure" => Some(Block::Figure),
            ":::tradeoff" => Some(Block::Tradeoff),
            ":::recap" => Some(Block::Recap),
            _ => None,
        };
        if let Some(m) = marker {
            let chunk = &body[chunk_start..offset];
            if !chunk.trim().is_empty() {
                blocks.push(Block::Html(chunk));
            }
            blocks.push(m);
            chunk_start = offset + line.len();
        }
        offset += line.len();
    }
    let tail = &body[chunk_start..];
    if !tail.trim().is_empty() {
        blocks.push(Block::Html(tail));
    }
    blocks
}

/// Render a markdown fragment to an HTML string (inline HTML like the `.var`
/// math spans passes through verbatim).
fn markdown(md: &str) -> String {
    let mut opts = Options::empty();
    opts.insert(Options::ENABLE_TABLES);
    opts.insert(Options::ENABLE_SMART_PUNCTUATION);
    let mut out = String::new();
    html::push_html(&mut out, Parser::new_ext(md, opts));
    out
}

/// A string as a valid, escaped Rust `&str` literal.
fn lit(s: &str) -> String {
    format!("{s:?}")
}
